server:
  port: 8086

spring:
  application:
    name: admin-server
  boot:
    admin:
      context-path: /admin
#      discovery:
#        enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
#      base-path: /${spring.application.name}/actuator
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: /logs/admin-server.log
